language: rust
sudo: true
dist: xenial
os: osx
osx_image: xcode10.3

install:
#   - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
#   - sudo apt-get -y update
#   - sudo apt-get -y install gcc-arm-embedded
  - rustup target add armv7r-none-eabi
  - rustup component add rustfmt

addons:
  homebrew:
    packages: arm-gcc-bin
    taps: osx-cross/arm

cache: 
#   - apt
  - cargo

rust:
- stable

script:
  - cargo build
  - make all
